name: payment npm publish

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/cart

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, eslint, prettier, typescript]
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependency install
        run: pnpm install

      - name: Compile
        run: pnpm build

      - name: Publish
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
