name: payment npm publish

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/payment

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.10.0
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependency install
        run: pnpm install

      - name: Compile
        run: pnpm build

      - name: Publish
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
